configuration:  
  projectName: reservation-client
server:
  port: 8050
message:
  greeting: Hello from the reservation-client!
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: reservations
          consumer:
            durableSubscription: true
  rabbitmq:
    addresses: amqp://localhost:5672