configuration:  
  projectName: reservation-service
server:
  port: 8020
message:
  greeting: Hello from the reservation-service!
spring:
    redis:
        host: "localhost"
    cloud:
        stream:
            default-binder: redis  
            bindings:
                input: 
                    destination: reservations