configuration:  
  projectName: reservation-service
server:
  port: 8000
message:
  greeting: Hello from the reservation-service!
spring:
    cloud:
        stream:
            default-binder: rabbit  

