configuration:  
  projectName: reservation-client
server:
  port: 8050
message:
  greeting: Hello from the reservation-client!
spring:
  cloud:
    stream:
        bindings:
            output: reservations