configuration:  
  projectName: reservation-service
server:
  port: 8020
message:
  greeting: Hello from the reservation-service!
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: reservations
          consumer:
            durableSubscription: true
  rabbitmq:
    addresses: amqp://192.168.99.100:5672
    username: admin
    password: admin
