configuration:  
  projectName: reservation-client
server:
  port: 8050
message:
  greeting: Hello from the reservation-client!
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: reservations
          consumer:
            durableSubscription: true
  rabbitmq:
    addresses: amqp://192.168.99.100:5672
    username: admin
    password: admin
