configuration:  
  projectName: reservation-service
server:
  port: 8020
message:
  greeting: Hello from the reservation-service!
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: reservations
          consumer:
            durableSubscription: true
  rabbitmq:
    addresses: amqp://localhost:5672